name: subscription_cli
description: Help you to manage your subscription, such as upgrade some package/app to the latest version.
version: 0.1.1
repository: https://github.com/CaiJingLong/subscription_cli.git

environment:
  sdk: ^3.0.0

dependencies:
  archive: ^3.4.9
  args: ^2.4.2
  glob: ^2.1.2
  http: ^1.1.0
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

executables:
  subscription_cli:
  scli: subscription_cli