name: subscription_cli
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/CaiJingLong/subscription_cli.git

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  subscription_cli:
  scli: subscription_cli