config:
  githubToken: ${GITHUB_TOKEN}
  proxy:
    host: localhost
    port: 7890

jobs:
  - name: m3u8
    type: github-release
    owner: Caijinglong
    repo: m3u8_download
    output: "output/m3u8"
    enabled: true
    params:
      platform: macos
    asset: "#{platform}_#{version}.tar.gz"
    post:
      src: bin/m3u8_download.exe
      target: /usr/local/bin/m3u8_download
      mode: "0755"
    overwrite: true
  - name: kap
    type: github-release
    owner: wulkano
    repo: Kap
    output: "output/kap"
    enabled: false
    asset: "Kap-*-x64.dmg"
    post:
      src: Kap.app
      target: /Applications/Kap.app
    overwrite: true
  - name: scli
    type: github-release
    asset: 'mac*'
    url: https://github.com/CaiJingLong/subscription_cli
    output: ./output/scli
    post:
      mode: +x
      target: scli
    overwrite: true