config:
  githubToken: ${GITHUB_TOKEN}
  proxy:
    host: localhost
    port: 7890

jobs:
  - name: m3u8
    type: github-release
    owner: Caijinglong
    repo: m3u8_download
    output: "output/m3u8"
    enabled: true
    params:
      platform: macos
    asset: "#{platform}_#{version}.tar.gz"
    post:
      src: bin/m3u8_download.exe
      target: /usr/local/bin/m3u8_download
      mode: "+x"
    overwrite: true
  - name: kap
    type: github-release
    enabled: false
    # owner: wulkano
    # repo: Kap
    url: https://github.com/wulkano/Kap
    asset: "Kap-*-x64.dmg"
    output: "output/kap"
    post:
      src: Kap.app
      target: /Applications/Kap.app
    overwrite: true
  - name: picgo
    type: github-release
    owner: Molunerfinn
    repo: PicGo
    output: "output/picgo"
    enabled: true
    asset: "*-x64.dmg"
    post:
      src: PicGo.app
    overwrite: true
  - name: scli
    type: github-release
    asset: "mac*"
    url: https://github.com/CaiJingLong/subscription_cli
    output: ./output/scli
    overwrite: true
    post:
      mode: +x
      target: scli
      src: scli
