name: Auto delete branch after PR is closed.

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');
            octokit.git.deleteRef({
              owner,
              repo,
              ref: `heads/${branch}`
            });
